#!/bin/bash

cd "$(dirname "$0")"

# 处理命令
case "$1" in
    init)
        make init
        ;;
    addchain)
        shift
        while [[ "$#" -gt 0 ]]; do
            case "$1" in
                -k)
                    key="$2"
                    shift 2
                    ;;
                -d)
                    data="$2"
                    shift 2
                    ;;
                *)
                    echo "不明參數: $1"
                    exit 1
                    ;;
            esac
        done
        echo "建立區塊: $key 及其值: $data"
        curl -s -X POST https://bc.wtechhk.xyz/upload -d '{"blockID": "'"$key"'", "data": "'"$data"'"}') 
        ;;
    *)
        echo "Usage: $0 {init|addchain}"
        exit 1
        ;;
esac
